### ISSUE TITLE
Group and project description

### ISSUE THREAD

**Issue by Dagic-zewdu** [damdafayton/group-project-spacehub#40]
In this project, we are a group of two (@Dagic-zewdu and @damdafayton). We added all the issues given in to [the kanban board.](https://github.com/damdafayton/group-project-spacehub/projects/1)

**Comment by Whoistolu** [comment]
### Hi Team,
@Dagic-zewdu and @damdafayton 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
